<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /**
         * 如果作为参数的 Promise 实例，自己定义了catch方法，那么它一旦被rejected，并不会触发Promise.all()的catch方法。
         * p1会resolved，p2首先会rejected，但是p2有自己的catch方法，该方法返回的是一个新的 Promise实例，
         * p2指向的实际上是这个实例。该实例执行完catch方法后，也会变成resolved，
         * 导致Promise.all()方法参数里面的两个实例都会resolved，因此会调用then方法指定的回调函数，
         * 而不会调用catch方法指定的回调函数。
         */
        const p1 = new Promise((resolve, reject) => {
            resolve('hello');
        }).then(result => result).catch(e => e);

        const p2 = new Promise((resolve, reject) => {
            throw new Error('报错了');
        }).then(result => result).catch(e => e);

        Promise.all([p1, p2]).then(result => console.log(result)).catch(e => console.log(e));

        /**
         * 打印结果：
         * ["hello", Error: 报错了]
         */
    </script>
</body>

</html>